import fully

BATCH_SIZE = 512
EPOCHS = 100
LR = 0.1
W_DECAY = 5e-4#2e-4
N_WORKERS = 2
MOMENTUM = 0.9#0.9


CHANNELS = 32 # MUST BE AN EVEN NUMBER
N_BLOCK  = 20
N_CLASSES = 10


MODEL = fully.FullyReversible(CHANNELS, N_BLOCK, N_CLASSES)